package coursework;

import java.util.ArrayList;
import java.util.Arrays;

/**
 *
 * Gets the required details form the programme file
 *
 * @author Matthew Osborne
 *
 */
public class GenerateProgramme {

	private static ArrayList<String> programmeArray;
	private static ArrayList<String>[] allMoves;
	private static ArrayList<String> playerIDs;
	private static ArrayList<String> playerMoves;

	/**
	 * @param fileArray
	 *            Array generated by ReadFile
	 */
	public GenerateProgramme(ArrayList<String> fileArray) {
		programmeArray = fileArray;
		splitArray();
	}

	/**
	 * Splits the array into names and moves.
	 */
	@SuppressWarnings("unchecked")
	public void splitArray() {
		int rounds = programmeArray.size();
		allMoves = new ArrayList[rounds - 1];
		String[] names = programmeArray.get(0).split("\\s+");
		for (int i = 1; i < rounds; i++) {
			String[] moves = programmeArray.get(i).split("\\s+");
			playerMoves = new ArrayList<String>(Arrays.asList(moves));
			allMoves[i - 1] = playerMoves;
		}
		playerIDs = new ArrayList<String>(Arrays.asList(names));
	}

	/**
	 *
	 * Gets the player IDs of the programme.
	 *
	 *
	 * @return playerIDs ArrayList of playerIDs
	 */
	public static ArrayList<String> getPlayerIDs() {
		return playerIDs;
	}

	/**
	 *
	 * Gets the player moves of the programme.
	 *
	 * @return allMoves ArrayList of player moves
	 */
	public static ArrayList<String>[] getPlayerMoves() {
		return allMoves;
	}

	/**
	 *
	 * Gets the number of rounds in the programme.
	 *
	 * @return allMoves.length The number of rounds in the programme.
	 */
	public static int getRounds() {
		return allMoves.length;
	}

}
